#!/usr/bin/env python

import os
import sys
from subprocess import check_output, call

cwd = os.path.abspath(os.path.dirname(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(cwd, '../../'))
sys.path.append(PROJECT_ROOT)

if __name__ == '__main__':
    branch = check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).rstrip().decode('utf-8')
    if branch == 'master':
        print ('cant commit directly to master existing')
        exit(1)
    exit(0)