
CHILD_ADDITION_SUCCEEDED = "CHILD_ADDITION_SUCCEEDED"
PERSON_NOT_FOUND = "PERSON_NOT_FOUND"
CHILD_ADDITION_FAILED = "CHILD_ADDITION_FAILED"
NONE_FOUND = None
INVALID_RELATION_TYPE = "Please enter Valid Relationship Type"
GENDER_MALE = "MALE"
GENDER_FEMALE = "FEMALE"
